Dev-vpc-cidrblock              = "10.0.0.0/16"
Dev-vpc-instance-tenency       = "default"
Dev-subnet-1-cidrblock         = "10.0.1.0/24"
Dev-subnet-1-availability-zone = "us-east-1"
Dev-subnet-2-cidrblock         = "10.0.2.0/24"
Dev-subnet-2-availability-zone = "us-east-2b"